//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub total_price: Decimal,
    pub status: i32,
    pub shipping_status: i32,
    pub shipping_company: Option<String>,
    pub tracking_number: Option<String>,
    pub payment_status: i32,
    pub payment_method: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub paid_at: Option<DateTimeWithTimeZone>,
    pub shipped_at: Option<DateTimeWithTimeZone>,
    pub delivered_at: Option<DateTimeWithTimeZone>,
    pub canceled_at: Option<DateTimeWithTimeZone>,
    pub refunded_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub shipping_address: String,
    #[sea_orm(column_type = "Text")]
    pub billing_address: String,
    pub discount: Option<Decimal>,
    pub coupon_code: Option<String>,
    pub gift_card_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
